strings_tare = {
	'Dies on Trash',
	'Mentions BoE Drop',
	'Threatens to Stop Raiding',
	'Unprepared',
	'Loot Drop',
	'Dies First',
	'Mentions DPS',
	'Mythics?',
	'Mentions School',
	'Mentions Alt Gearing',
	'Titanforge',
	'Pulls Boss or Trash',
	'X% Upgrade',
	'Asks for Loot',
	'Needs Re-Explaination',
	'That\'s What She Said',
	'X Keyed',
	'Inappropriate Comment',
	'RNG',
	'Complains About Loot',
	'Late to Raid',
	'Not Feeling Well',
	'Wastes Cooldowns'
	}
	
strings_generic = {
	'Tare Dies on Trash',
	'Mar Mentions Shaman',
	'Forgets You Can\'t Trade Upgrade',
	'Becca Complains About Feasts',
	'Spazz \"Relaxation\" Break',
	'Tare Dies First on Boss',
	'Tare Mentions DPS',
	'Mythics?',
	'Jibbish Never Speaks',
	'Tare Mentions Gearing Alt',
	'Sieb Mic Breathing',
	'Someone Pulls Before Tank',
	'X% Upgrade',
	'Hellravage Mentions Job',
	'Spazz AFK for >2 Minutes',
	'That\'s What She Said',
	'Joe Gets No Loot',
	'Becca Complains about Performance',
	'RNG Blamed for Obvious Tunneling Death',
	'Someone Complains about Loot',
	'Sieb says \"oot\"',
	'Tare is Late',
	'Mispronounce Alaiss/Siala',
	'Rollback Asks for Dispel/Heal'
	}
	
test = {0, 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24}