strings_generic = {
	'>100k DPS on Trash',
	'\"DBM Pull\" >=3 Times Before Timer',
	'\"Go to Narnia\"',
	'\"That\'s What She Said\"',
	'Azu Way Ahead in DPS',
	'Bamboo Speaks',
	'BoE Drop Causes AH Drama',
	'Comment about Stream',
	'Forgets Bonus Rolls',
	'Extended Raid Hours',
	'Inappropriate Comment',
	'Joe Gets No Loot',
	'Mispronounce \'Alaiss\'',
	'Mythics?',
	'Open Mic + Mechanical Keyboard',
	'Ride Druid on Run Back',
	'Sieb Loses Gambling',
	'Sieb Mic Breathing',
	'Sieb Says \"oot\"',
	'Someone Asks for Auction Mount',
	'Someone Asks for Mailbox',
	'Someone Complains about Loot',
	'Someone Loses >50k Gambling',
	'Weed Reference',
	'Wife/Child Aggro',
	'Wipe on Farm Boss',
	'X% Upgrade',
	'Zes Cuts Under- performers',
	'Zes Forgets to Turn Repairs On',
	'Zes Gets a Titan/Warforge',
	}
