strings_generic = {
	'Tare Dies on Trash',
	'Mar Mentions Shaman',
	'Forgets You Can\'t Trade Upgrade',
	'Becca Complains About Feasts',
	'Spazz \"Relaxation\" Break',
	'Tare Dies First on Boss',
	'Tare Mentions DPS',
	'Mythics?',
	'Jibbish Never Speaks',
	'Tare Mentions Gearing Alt',
	'Sieb Mic Breathing',
	'Someone Pulls Before Tank',
	'X% Upgrade',
	'Hellravage Mentions Job',
	'Spazz AFK for >2 Minutes',
	'That\'s What She Said',
	'Joe Gets No Loot',
	'Becca Complains about Performance',
	'RNG Blamed for Obvious Tunneling Death',
	'Someone Complains about Loot',
	'Sieb says \"oot\"',
	'Tare is Late',
	'Mispronounce Alaiss/Siala',
	'Rollback Asks for Dispel/Heal',
	'Inappropriate Comment',
	'Not Feeling Well',
	'Wastes Cooldowns',
	'Tare Gets Titanforge',
	'Move to Discord',
	'Someone Can\'t Get in WoW Chat',
	'Cloak Nobody Wants',
	'Tank Beats a DPS in Damage',
	'Titan Slayers Join',
	'Forgot Bonus Rolls',
	'Wipe on Farm Boss',
	'Becca Backseat Healing',
	'Misunder- stood Mechanics',
	'Someone Explains Mechanic Wrong',
	'Someone Late',
	'Inexplicable Absence'
	}

test = {0, 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24}